
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.define "manager" do |manager|
      manager.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
      end
    manager.vm.box = "ubuntu/focal64"
    manager.vm.box_check_update = false
    manager.vm.network "private_network", ip: "192.168.33.10"
    manager.vm.hostname = "manager"
  end
    config.vm.define "node01" do |node01|
      node01.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "4096"
        vb.cpus = 2
      end
    node01.vm.box = "ubuntu/focal64"
    node01.vm.box_check_update = false
    node01.vm.network "private_network", ip: "192.168.33.20"
    node01.vm.hostname = "node01"
    node01.vm.network "forwarded_port", guest:80, host:8080
    node01.vm.network "forwarded_port", guest:8081, host:8081
    node01.vm.network "forwarded_port", guest:8087, host:8087
    
  end
    config.vm.define "node02" do |node02|
      node02.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.memory = "2048"
      end
    node02.vm.box = "ubuntu/focal64"
    node02.vm.box_check_update = false
    node02.vm.network "private_network", ip: "192.168.33.30"
    node02.vm.hostname = "node02"
    node02.vm.network "forwarded_port", guest: 5432, host: 5433
  end
end